apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pawid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres-service 5432; do
                echo "Waiting for postgres...";
                sleep 3;
              done
      containers:
        - name: backend
          image: mihajlovb/pawid-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pawid-config
            - secretRef:
                name: pawid-secret
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /api/dogs
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/dogs
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: pawid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi