apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pawid
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mihajlovb/CICD-Project
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: pawid

  syncPolicy:
    automated:
      prune: true        # бриши ресурси кои се отстранети од git
      selfHeal: true     # врати промени направени рачно на кластерот
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
